language: java

# The trusty build environment allows for more memory, see https://docs.travis-ci.com/user/reference/overview/
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx6g"
  matrix:
    - TEST=RunBerlinScenarioTest#mainWithEquil
    - TEST=RunBerlinScenarioTest#santiago1pct0it
    - TEST=RunBerlinScenarioTest#santiago1pct2it

script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
